# Generated by Django 4.2 on 2023-04-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_apartment_rent'),
        ('leads', '0011_remove_lead_email_remove_lead_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_leads', to='properties.apartment'),
        ),
    ]
