# Generated by Django 4.2 on 2023-04-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='apartment',
        ),
    ]
