# Generated by Django 4.2 on 2023-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_is_organisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_lead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
