# Generated by Django 4.2 on 2023-04-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_is_lead_user_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_organisor',
        ),
    ]
