# Generated by Django 4.2 on 2023-04-25 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_remove_bill_month_remove_bill_unit_remove_bill_year_and_more'),
        ('leads', '0016_remove_lead_is_lead_remove_lead_is_organisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=15)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.apartment')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
