# Generated by Django 4.2 on 2023-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_apartment_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='lead_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
