# Generated by Django 4.2 on 2023-04-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_apartment_lead_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='lead_user_id',
        ),
    ]
