# Generated by Django 4.2 on 2023-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_apartment_lead_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='default_apartment.jpg', upload_to='apartments/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default_property.jpg', upload_to='properties/'),
        ),
    ]
