# Generated by Django 4.2 on 2023-04-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_apartment_image_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_utility.jpg', upload_to='utilities/')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='properties.apartment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='properties.property')),
            ],
        ),
    ]
