# Generated by Django 4.2 on 2023-04-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_utility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='image',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('image', models.ImageField(default='default_bill.jpg', upload_to='bills/')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='properties.utility')),
            ],
        ),
    ]
