# Generated by Django 4.2 on 2023-04-24 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_bill_amount_remove_bill_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.PositiveSmallIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
