# Generated by Django 4.2 on 2023-04-24 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_bill_total_bill_amount_bill_month_bill_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
    ]
