# Generated by Django 4.2 on 2023-04-24 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
    ]
