# Generated by Django 4.2 on 2023-04-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year',
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
